name: Deploy TravelVN via FTP

on:
push:
branches:
- main # Thay bằng 'master' nếu nhánh chính của bạn tên là master

jobs:
web-deploy:
name: Deploy to cPanel
runs-on: ubuntu-latest
steps:
- name: Get latest code
uses: actions/checkout@v4

- name: Sync files via FTP
uses: SamKirkland/FTP-Deploy-Action@v4.3.5
with:
server: ${{ secrets.ftpupload.net}}
username: ${{ secrets.if0_41728842}}
password: ${{ secrets.ddEXbUD0grfbxWx}}
local-dir: ./
server-dir: /public_html/ # Đây là thư mục gốc web trên cPanel, hãy đổi nếu host của bạn dùng đường dẫn khác
exclude: |
**/.git*
**/.git*/**
README.md
.env # Loại trừ file môi trường để không ghi đè cấu hình database thực tế trên host